version: '3.4'

services:
  web:
    depends_on:
      - db
      - api
    build:
      context: webapp
    hostname: todolist-webapp
    stdin_open: true
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./webapp:/code
    networks:
      - todolist-network

  api:
    depends_on:
      - db
    build:
      context: api
    hostname: todolist-api
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./api:/code
    networks:
      - todolist-network

  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - todolist-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@todolist.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    restart: always
    volumes:
      - pgadmin-data:/root/.pgadmin
    networks:
      - todolist-network

volumes:
  db-data:
  pgadmin-data:

networks:
  todolist-network:
    driver: bridge